<?php
use \Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Messenger\MessengerInterface;

/**
 * Implements hook_form_FORM_ID_alter().
 * Shows refund form.
 */
function uc_paylike_form_uc_credit_terminal_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  // TODO: find a better way to get an order
  $order = $form_state->getBuildInfo()['args'][0];
  $form_state->set('uc_order', $order);

  // Check if Paylike payment method was used
  /** @var \Drupal\uc_payment\PaymentMethodPluginInterface $plugin */
  $plugin = \Drupal::service('plugin.manager.uc_payment.method')->createFromOrder($order);
  $paymentMethod = $plugin->getPluginId();
  if ($paymentMethod != 'paylike_gateway') return;

  $options = array();
  $form['specify_card']['#weight'] = 100;
  $form['specify_card']['#open'] = false;

  if (isset($order->data->cc_txns['authorizations'])) {
    foreach ($order->data->cc_txns['authorizations'] as $auth_id => $data) {
      if (!empty($data['captured']) && empty($data['refunded'])) {
        $options[$auth_id] = t('@auth_id - @date - @amount captured', [
          '@auth_id' => strtoupper($auth_id),
          '@date' => \Drupal::service('date.formatter')->format($data['captured'], 'short'),
          '@amount' => uc_currency_format($data['capturedAmount'])
        ]);
      }
    }
  }

  if (!empty($options)) {
    $form['paylike_refund'] = [
      '#type' => 'details',
      '#title' => t('Paylike refund'),
      '#open' => true,
    ];
    $form['paylike_refund']['refund_transaction'] = array(
      '#type' => 'radios',
      '#title' => t('Select authorization to refund'),
      '#options' => $options,
    );

    $form['paylike_refund']['actions'] = array('#type' => 'actions');
    $form['paylike_refund']['actions']['refund'] = array(
      '#type' => 'submit',
      '#value' => t('Refund'),
      '#validate' => array('uc_paylike_refund_form_validate'),
      '#submit' => array('uc_paylike_refund_form_submit'),
    );
  }
}

function uc_paylike_refund_form_validate($form, FormStateInterface $form_state) {
  $amount = $form_state->getValue('amount');
  if (!$amount || $amount <= 0) {
    $form_state->setError($form['amount'], 'Amount must be a digital greater than 0.');
  }
  if (!$form_state->getValue('refund_transaction')) {
    $form_state->setError($form['paylike_refund']['refund_transaction'], 'Select a transaction to refund please.');
  }
}

function uc_paylike_refund_form_submit($form, FormStateInterface $form_state) {
  $user = \Drupal::currentUser();
  $order = $form_state->get('uc_order');
  /** @var \Drupal\uc_payment\PaymentMethodPluginInterface $plugin */
  $plugin = \Drupal::service('plugin.manager.uc_payment.method')->createFromOrder($order);
  $transactionId = $form_state->getValue('refund_transaction');
  $amount = $form_state->getValue('amount');
  $result = $plugin->refund($transactionId, uc_currency_format($amount, false, false, false));
  $messenger = \Drupal::messenger();
  if ($result['successful']) {
    $message = t('Refund successfully made for @amount.', ['@amount' => uc_currency_format($amount)]);
    $messenger->addMessage($message);
    uc_order_comment_save($order->id(), $user->id(), $message, 'order');
    $txns = $order->data->cc_txns;
    $txns['authorizations'][$transactionId]['refunded'] = \Drupal::time()->getRequestTime();
    $order->data->cc_txns = $txns;
    $order->save();
  } else {
    $message = t('Refund failed. Transaction ID: @id. Message: @message', ['@id' => $transactionId, '@message' => $result['error']]);
    $messenger->addMessage($message, $messenger::TYPE_ERROR);
    uc_order_comment_save($order->id(), $user->id(), $message, 'admin');
  }
}
